openapi: 3.2.0
info:
  description: 'The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:


    - The marketplaces a seller can list in

    - The default language and currency of a marketplace

    - Whether the seller has suspended listings


    Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API''s operations, data types, and schemas.'
  version: v1
  title: Selling Partner Sellers API
  contact:
    name: Selling Partner API Developer Support
    url: https://sellercentral.amazon.com/gp/mws/contactus.html
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://sellingpartnerapi-na.amazon.com
tags:
- name: sellers
paths:
  /sellers/v1/marketplaceParticipations:
    get:
      tags:
      - sellers
      description: 'Returns a list of marketplaces where the seller can list items and information about the seller''s participation in those marketplaces.


        **Usage Plan:**


        | Rate (requests per second) | Burst |

        | ---- | ---- |

        | 0.016 | 15 |


        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).'
      operationId: getMarketplaceParticipations
      responses:
        '200':
          description: Marketplace participations successfully retrieved.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          x-amzn-api-sandbox:
            static:
            - request:
                parameters: {}
              response:
                payload:
                - marketplace:
                    id: ATVPDKIKX0DER
                    countryCode: US
                    name: Amazon.com
                    defaultCurrencyCode: USD
                    defaultLanguageCode: en_US
                    domainName: www.amazon.com
                  storeName: BestSellerStore
                  participation:
                    isParticipating: true
                    hasSuspendedListings: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '400':
          description: Request has missing or invalid parameters and cannot be parsed.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '403':
          description: 403 can be caused for reasons like Access Denied, Unauthorized, Expired Token, Invalid Signature or Resource Not Found.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '404':
          description: The resource specified does not exist.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '413':
          description: The request size exceeded the maximum accepted size.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '415':
          description: The entity of the request is in a format not supported by the requested resource.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '429':
          description: The frequency of requests was greater than allowed.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '500':
          description: Encountered an unexpected condition which prevented the server from fulfilling the request.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        '503':
          description: Temporary overloading or maintenance of the server.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
  /sellers/v1/account:
    get:
      tags:
      - sellers
      description: 'Returns information about a seller account and its marketplaces.


        **Usage Plan:**


        | Rate (requests per second) | Burst |

        | ---- | ---- |

        | 0.016 | 15 |


        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).'
      operationId: getAccount
      responses:
        '200':
          description: Success.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          x-amzn-api-sandbox:
            static:
            - request:
                parameters: {}
              response:
                payload:
                  businessType: PRIVATE_LIMITED
                  marketplaceParticipationList:
                  - marketplace:
                      id: ATVPDKIKX0DER
                      name: United States
                      countryCode: US
                      domainName: www.amazon.com
                    storeName: BestSellerStore
                    participation:
                      isParticipating: true
                      hasSuspendedListings: false
                  sellingPlan: PROFESSIONAL
                  business:
                    name: BestSeller Inc.
                    nonLatinName: ベストセラー株式会社
                    registeredBusinessAddress:
                      addressLine1: 123 Main St
                      addressLine2: Suite 500
                      city: Seattle
                      stateOrProvinceCode: WA
                      postalCode: '98101'
                      countryCode: US
                    companyRegistrationNumber: '123456789'
                    companyTaxIdentificationNumber: '987654321'
                  primaryContact:
                    name: John Doe
                    nonLatinName: ジョン・ドゥ
                    address:
                      addressLine1: 456 Oak St
                      addressLine2: Apt 12
                      city: Seattle
                      stateOrProvinceCode: WA
                      postalCode: '98102'
                      countryCode: US
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
              example:
                payload:
                  businessType: PRIVATE_LIMITED
                  marketplaceParticipationList:
                  - marketplace:
                      id: ATVPDKIKX0DER
                      name: United States
                      countryCode: US
                      domainName: www.amazon.com
                    storeName: BestSellerStore
                    participation:
                      isParticipating: true
                      hasSuspendedListings: false
                  sellingPlan: PROFESSIONAL
                  business:
                    name: BestSeller Inc.
                    nonLatinName: ベストセラー株式会社
                    registeredBusinessAddress:
                      addressLine1: 123 Main St
                      addressLine2: Suite 500
                      city: Seattle
                      stateOrProvinceCode: WA
                      postalCode: '98101'
                      countryCode: US
                    companyRegistrationNumber: '123456789'
                    companyTaxIdentificationNumber: '987654321'
                  primaryContact:
                    name: John Doe
                    nonLatinName: ジョン・ドゥ
                    address:
                      addressLine1: 456 Oak St
                      addressLine2: Apt 12
                      city: Seattle
                      stateOrProvinceCode: WA
                      postalCode: '98102'
                      countryCode: US
        '400':
          description: Request has missing or invalid parameters and cannot be parsed.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          x-amzn-api-sandbox:
            static:
            - request:
                parameters: {}
              response:
                errors:
                - code: InvalidInput
                  message: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '403':
          description: Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '404':
          description: The resource specified does not exist.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '413':
          description: The request size exceeded the maximum accepted size.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '415':
          description: The request payload is in an unsupported format.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '429':
          description: The frequency of requests was greater than allowed.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '500':
          description: An unexpected condition occurred that prevented the server from fulfilling the request.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
        '503':
          description: Temporary overloading or maintenance of the server.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
components:
  schemas:
    Marketplace:
      type: object
      required:
      - id
      - name
      - countryCode
      - defaultCurrencyCode
      - defaultLanguageCode
      - domainName
      properties:
        id:
          type: string
          description: The encrypted marketplace value.
        name:
          type: string
          description: The marketplace name.
        countryCode:
          type: string
          description: The ISO 3166-1 alpha-2 format country code of the marketplace.
          pattern: ^([A-Z]{2})$
        defaultCurrencyCode:
          type: string
          description: The ISO 4217 format currency code of the marketplace.
        defaultLanguageCode:
          type: string
          description: The ISO 639-1 format language code of the marketplace.
        domainName:
          type: string
          description: The domain name of the marketplace.
      description: Information about an Amazon marketplace where a seller can list items and customers can view and purchase items.
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: string
          description: An error code that identifies the type of error that occurred.
        message:
          type: string
          description: A message that describes the error condition in a human-readable form.
        details:
          type: string
          description: Additional details that can help you understand or fix the issue.
      description: Error response returned when the request is unsuccessful.
    MarketplaceParticipationList:
      type: array
      description: List of marketplace participations.
      items:
        $ref: '#/components/schemas/MarketplaceParticipation'
    Business:
      type: object
      description: Information about the seller's business. Certain fields may be omitted depending on the seller's `businessType`.
      required:
      - name
      - registeredBusinessAddress
      properties:
        name:
          type: string
          description: The registered business name.
        registeredBusinessAddress:
          $ref: '#/components/schemas/Address'
          description: The registered business address.
        companyRegistrationNumber:
          type: string
          description: The seller's company registration number, if applicable. This field will be absent for individual sellers and sole proprietorships.
        companyTaxIdentificationNumber:
          type: string
          description: The seller's company tax identification number, if applicable. This field will be present for certain business types only, such as sole proprietorships.
        nonLatinName:
          type: string
          description: The non-Latin script version of the registered business name, if applicable.
    GetAccountResponse:
      description: The response schema for the `getAccount` operation.
      type: object
      properties:
        payload:
          $ref: '#/components/schemas/Account'
        errors:
          description: The errors encountered by the `getAccount` operation.
          $ref: '#/components/schemas/ErrorList'
    Address:
      type: object
      description: Represents an address
      required:
      - addressLine1
      - countryCode
      properties:
        addressLine1:
          type: string
          description: Street address information.
        addressLine2:
          type: string
          description: Additional street address information.
        countryCode:
          type: string
          description: The country code in two-character ISO 3166-1 alpha-2 format.
        stateOrProvinceCode:
          type: string
          description: The state or province code.
        city:
          type: string
          description: The city.
        postalCode:
          type: string
          description: The postal code.
    MarketplaceParticipation:
      type: object
      required:
      - marketplace
      - participation
      - storeName
      properties:
        marketplace:
          $ref: '#/components/schemas/Marketplace'
        participation:
          $ref: '#/components/schemas/Participation'
        storeName:
          type: string
          description: The name of the seller's store as displayed in the marketplace.
    Participation:
      type: object
      required:
      - hasSuspendedListings
      - isParticipating
      properties:
        isParticipating:
          type: boolean
          description: If `true`, the seller participates in the marketplace. Otherwise `false`.
        hasSuspendedListings:
          type: boolean
          description: Specifies if the seller has suspended listings. `true` if the seller Listing Status is set to Inactive, otherwise `false`.
      description: Information that is specific to a seller in a marketplace.
    ErrorList:
      type: array
      description: A list of error responses returned when a request is unsuccessful.
      items:
        $ref: '#/components/schemas/Error'
    PrimaryContact:
      type: object
      description: Information about the seller's primary contact.
      required:
      - name
      - address
      properties:
        name:
          type: string
          description: The full name of the seller's primary contact.
        address:
          $ref: '#/components/schemas/Address'
          description: The primary contact's residential address.
        nonLatinName:
          type: string
          description: The non-Latin script version of the primary contact's name, if applicable.
    GetMarketplaceParticipationsResponse:
      type: object
      properties:
        payload:
          description: The payload for the `getMarketplaceParticipations` operation.
          $ref: '#/components/schemas/MarketplaceParticipationList'
        errors:
          description: The errors encountered by the `getMarketplaceParticipations` operation.
          $ref: '#/components/schemas/ErrorList'
      description: The response schema for the `getMarketplaceParticipations` operation.
    Account:
      description: The response schema for the `getAccount` operation.
      type: object
      required:
      - businessType
      - sellingPlan
      - marketplaceParticipationList
      properties:
        marketplaceParticipationList:
          $ref: '#/components/schemas/MarketplaceParticipationList'
        businessType:
          type: string
          description: The type of business registered for the seller account.
          enum:
          - CHARITY
          - CRAFTSMAN
          - NATURAL_PERSON_COMPANY
          - PUBLIC_LISTED
          - PRIVATE_LIMITED
          - SOLE_PROPRIETORSHIP
          - STATE_OWNED
          - INDIVIDUAL
          x-docgen-enum-table-extension:
          - value: CHARITY
            description: The business is registered as a charity.
          - value: CRAFTSMAN
            description: The business is registered as a craftsman.
          - value: NATURAL_PERSON_COMPANY
            description: The business is a natural person company.
          - value: PUBLIC_LISTED
            description: The business is a publicly listed company.
          - value: PRIVATE_LIMITED
            description: The business is a private limited company.
          - value: SOLE_PROPRIETORSHIP
            description: The business is a sole proprietorship.
          - value: STATE_OWNED
            description: The business is state-owned.
          - value: INDIVIDUAL
            description: The entity is not a business but an individual.
        sellingPlan:
          type: string
          description: The selling plan details.
          enum:
          - PROFESSIONAL
          - INDIVIDUAL
          x-docgen-enum-table-extension:
          - value: PROFESSIONAL
            description: The seller has a professional selling plan.
          - value: INDIVIDUAL
            description: The seller has an individual selling plan.
        business:
          $ref: '#/components/schemas/Business'
        primaryContact:
          $ref: '#/components/schemas/PrimaryContact'
