openapi: 3.2.0
info:
  description: 'The Selling Partner API for Tokens provides a secure way to access a customer''s PII (Personally Identifiable Information). You can call the Tokens API to get a Restricted Data Token (RDT) for one or more restricted resources that you specify. The RDT authorizes subsequent calls to restricted operations that correspond to the restricted resources that you specified.


    For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide).'
  version: '2021-03-01'
  title: Selling Partner Tokens API
  contact:
    name: Selling Partner API Developer Support
    url: https://sellercentral.amazon.com/gp/mws/contactus.html
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://sellingpartnerapi-na.amazon.com
tags:
- name: tokens
paths:
  /tokens/2021-03-01/restrictedDataToken:
    post:
      operationId: createRestrictedDataToken
      tags:
      - tokens
      description: 'Returns a Restricted Data Token (RDT) for one or more restricted resources that you specify. A restricted resource is the HTTP method and path from a restricted operation that returns Personally Identifiable Information (PII), plus a dataElements value that indicates the type of PII requested. See the Tokens API Use Case Guide for a list of restricted operations. Use the RDT returned here as the access token in subsequent calls to the corresponding restricted operations.


        **Usage Plan:**


        | Rate (requests per second) | Burst |

        | ---- | ---- |

        | 1 | 10 |


        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).'
      responses:
        '200':
          description: Success.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          x-amzn-api-sandbox:
            static:
            - request:
                parameters:
                  body:
                    value:
                      targetApplication: amzn1.sellerapps.app.target-application
                      restrictedResources:
                      - method: GET
                        path: /orders/v0/orders/{orderId}/address
              response:
                restrictedDataToken: Atz.sprdt|IQEBLjAsAhRmHjNgHpi0U-Dme37rR6CuUpSR
                expiresIn: 3600
            - request:
                parameters:
                  body:
                    value:
                      restrictedResources:
                      - method: GET
                        path: /orders/v0/orders/943-12-123434/address
              response:
                restrictedDataToken: Atz.sprdt|AODFNESLjAsAhRmHjNgHpi0U-Dme37rR6CuUpSR
                expiresIn: 3600
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRestrictedDataTokenResponse'
        '400':
          description: Request has missing or invalid parameters and cannot be parsed.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          x-amzn-api-sandbox:
            static:
            - request:
                parameters:
                  body:
                    value:
                      targetApplication: amzn1.sellerapps.app.target-application
                      restrictedResources:
                      - method: ''
                        path: /orders/v1/orders/902-1845936-5435065/address
              response:
                errors:
                - code: InvalidRequest
                  message: Request is missing or has invalid parameters
                  details: Resource not provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '401':
          description: The request's Authorization header is not formatted correctly or does not contain a valid token.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '403':
          description: Indicates that access to the resource is forbidden. Possible reasons include Access Denied, Unauthorized, Expired Token, or Invalid Signature.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '404':
          description: The specified resource does not exist.
          headers:
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '415':
          description: The request payload is in an unsupported format.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '429':
          description: The frequency of requests was greater than allowed.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '500':
          description: An unexpected condition occurred that prevented the server from fulfilling the request.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '503':
          description: Temporary overloading or maintenance of the server.
          headers:
            x-amzn-RateLimit-Limit:
              description: 'Your rate limit (requests per second) for this operation.

                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.'
              schema:
                type: string
            x-amzn-RequestId:
              description: Unique request reference identifier.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRestrictedDataTokenRequest'
        description: The restricted data token request details.
        required: true
components:
  schemas:
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: string
          description: An error code that identifies the type of error that occurred.
        message:
          type: string
          description: A message that describes the error condition.
        details:
          type: string
          description: Additional details that can help the caller understand or fix the issue.
      description: An error response returned when the request is unsuccessful.
    CreateRestrictedDataTokenResponse:
      type: object
      description: The response schema for the createRestrictedDataToken operation.
      properties:
        restrictedDataToken:
          description: A Restricted Data Token (RDT). This is a short-lived access token that authorizes calls to restricted operations. Pass this value with the x-amz-access-token header when making subsequent calls to these restricted resources.
          type: string
        expiresIn:
          description: The lifetime of the Restricted Data Token, in seconds.
          type: integer
    ErrorList:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: A list of error responses returned when a request is unsuccessful.
    RestrictedResource:
      description: Model of a restricted resource.
      type: object
      required:
      - method
      - path
      properties:
        method:
          type: string
          description: The HTTP method in the restricted resource.
          enum:
          - GET
          - PUT
          - POST
          - DELETE
          x-docgen-enum-table-extension:
          - value: GET
            description: The GET method.
          - value: PUT
            description: The PUT method.
          - value: POST
            description: The POST method.
          - value: DELETE
            description: The DELETE method.
        path:
          type: string
          description: 'The path in the restricted resource. Here are some path examples:

            - ```/orders/v0/orders```. For getting an RDT for the getOrders operation of the Orders API. For bulk orders.

            - ```/orders/v0/orders/123-1234567-1234567```. For getting an RDT for the getOrder operation of the Orders API. For a specific order.

            - ```/orders/v0/orders/123-1234567-1234567/orderItems```. For getting an RDT for the getOrderItems operation of the Orders API. For the order items in a specific order.

            - ```/mfn/v0/shipments/FBA1234ABC5D```. For getting an RDT for the getShipment operation of the Shipping API. For a specific shipment.

            - ```/mfn/v0/shipments/{shipmentId}```. For getting an RDT for the getShipment operation of the Shipping API. For any of a selling partner''s shipments that you specify when you call the getShipment operation.'
        dataElements:
          type: array
          description: 'Indicates the type of Personally Identifiable Information requested. This parameter is required only when getting an RDT for use with the getOrder, getOrders, or getOrderItems operation of the Orders API. For more information, see the [Tokens API Use Case Guide](doc:tokens-api-use-case-guide). Possible values include:

            - **buyerInfo**. On the order level this includes general identifying information about the buyer and tax-related information. On the order item level this includes gift wrap information and custom order information, if available.

            - **shippingAddress**. This includes information for fulfilling orders.

            - **buyerTaxInformation**. This includes information for issuing tax invoices.'
          items:
            type: string
    CreateRestrictedDataTokenRequest:
      description: The request schema for the createRestrictedDataToken operation.
      type: object
      properties:
        targetApplication:
          type: string
          description: The application ID for the target application to which access is being delegated.
        restrictedResources:
          type: array
          description: 'A list of restricted resources.

            Maximum: 50'
          items:
            $ref: '#/components/schemas/RestrictedResource'
      required:
      - restrictedResources
